In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)
print(a%2)

[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]
[0.1 0.1 0.1 0.1]
[ 1  4  9 16]
[1 0 1 0]


In [5]:
print(np.add(a,b))
print(np.multiply(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))
print(np.power(a,2))
print(np.mod(a,2))

[11 22 33 44]
[ 10  40  90 160]
[ -9 -18 -27 -36]
[0.1 0.1 0.1 0.1]
[ 1  4  9 16]
[1 0 1 0]


In [13]:
a=np.array([1,2,3,4,5])

print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))
print(np.log2(a))
print(np.abs(np.array([-1,-2,-3])))
print(np.power(a,2))
print(np.round(3.14159,2))
print(np.sin(a), np.cos(a), np.tan(a))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[1 2 3]
[ 1  4  9 16 25]
3.14
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427] [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219] [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [14]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

x=np.array([-2,-1,0,1,2])
print(sigmoid(x))

[0.11920292 0.26894142 0.5        0.73105858 0.88079708]


In [16]:
y_true=np.array([3.0,5.0,2.5])
y_pred=np.array([2.8,5.2,2.0])

squared_error=(y_true-y_pred)**2
print(squared_error)
mse=np.mean(squared_error)
print(mse)

[0.04 0.04 0.25]
0.11000000000000004


# Broadcasting

In [17]:
a=np.array([1,2,3])
print(a+10)

[11 12 13]


In [18]:
a = np.array([[1, 2, 3], [4, 5, 6]])  # shape (2,3)
print(a + 5)
# shape (2,3) + scalar (treated as shape ()) -> scalar stretched to (2,3)

[[ 6  7  8]
 [ 9 10 11]]


In [19]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])       # shape (3,3)

row = np.array([10, 20, 30])          # shape (3,)

print(matrix + row)
# [[11 22 33]
#  [14 25 36]
#  [17 28 39]]

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [20]:
col = np.array([[1], [2], [3]])   # shape (3,1)
row = np.array([10, 20, 30])       # shape (3,)  -> treated as (1,3)

print(col + row)
# shapes: (3,1) and (1,3) -> both dims get stretched -> result (3,3)
# [[11 21 31]
#  [12 22 32]
#  [13 23 33]]

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])  # shape (2,3)
b = np.array([1,2])               # shape (2,)

print(a + b)  # ERROR!

In [26]:
A = np.ones((3, 4))     # shape (3, 4)
B = np.ones((4,))       # shape (4,)

result = A + B
print(result.shape)     # (3, 4)

# Rule check (right to left):
# dim -1: 4 vs 4 -> equal, OK
# dim -2: 3 vs (nothing, treated as 1) -> OK, stretch B's implicit "row" to 3

(3, 4)


In [27]:
A = np.ones((5, 1, 3))
B = np.ones((1, 4, 3))

result = A + B
print(result.shape)    # (5, 4, 3)

# dim -1: 3 vs 3 -> equal
# dim -2: 1 vs 4 -> one is 1 -> stretch to 4
# dim -3: 5 vs 1 -> one is 1 -> stretch to 5

(5, 4, 3)


Standardization

In [ ]:
#Standardization
X = np.array([[1, 200, 3000],
              [2, 150, 2500],
              [3, 300, 3200]])   # shape (3,3): 3 samples, 3 features

mean = X.mean(axis=0)   # shape (3,) -> mean of each column/feature
std = X.std(axis=0)     # shape (3,)

X_normalized = (X - mean) / std   # broadcasting: (3,3) - (3,) and (3,3) / (3,)
print(X_normalized)


[[-1.22474487 -0.26726124  0.33968311]
 [ 0.         -1.06904497 -1.35873244]
 [ 1.22474487  1.33630621  1.01904933]]
7.401486830834377e-17


Min Max Scaling

In [29]:
X = np.array([[10, 200], [20, 300], [30, 100]])

X_min = X.min(axis=0)
X_max = X.max(axis=0)

X_scaled = (X - X_min) / (X_max - X_min)
print(X_scaled)

[[0.  0.5]
 [0.5 1. ]
 [1.  0. ]]


In [30]:
outputs = np.array([[1.2, 0.5, 0.3],
                     [0.9, 0.8, 0.1]])  # shape (2,3): 2 samples, 3 neurons

bias = np.array([0.1, 0.2, 0.3])        # shape (3,): one bias per neuron

result = outputs + bias  # broadcasting adds bias to every sample's output
print(result)

[[1.3 0.7 0.6]
 [1.  1.  0.4]]


In [31]:
points = np.array([[0, 0], [3, 4], [1, 1]])   # shape (3,2)

# Compute distance of every point from origin
distances = np.sqrt(np.sum(points ** 2, axis=1))
print(distances)  # [0. 5. 1.414]

[0.         5.         1.41421356]


In [44]:
a=np.array([[1,2,3],
            [4,5,6]])

print(np.sum(a))
print(np.mean(a))
print(np.std(a))
print(np.var(a))
print(np.min(a))
print(np.max(a))
print(np.median(a))
print(np.argmin(a))
print(np.argmax(a))

print(a.sum(axis=0))
print(a.sum(axis=1))

21
3.5
1.707825127659933
2.9166666666666665
1
6
3.5
0
5
[5 7 9]
[ 6 15]


In [45]:
a = np.random.rand(4, 5)  # shape (4,5)
print(a.sum(axis=0).shape)  # (5,) -> the "4" disappeared
print(a.sum(axis=1).shape)  # (4,) -> the "5" disappeared

(5,)
(4,)


In [47]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.sum(axis=1))                  # [6 15] -> shape (2,)
print(a.sum(axis=1, keepdims=True))    # [[6] [15]] -> shape (2,1)

[ 6 15]
[[ 6]
 [15]]


In [46]:
a = np.array([[1, 2, 3], [4, 5, 6]])
row_sums = a.sum(axis=1, keepdims=True)  # shape (2,1)

normalized = a / row_sums   # (2,3) / (2,1) -> broadcasts correctly!
print(normalized)

[[0.16666667 0.33333333 0.5       ]
 [0.26666667 0.33333333 0.4       ]]


In [48]:
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))  # subtract max for numerical stability
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

logits = np.array([[2.0, 1.0, 0.1],
                    [1.0, 3.0, 0.2]])

probs = softmax(logits)
print(probs)
print(probs.sum(axis=1))  # [1. 1.] -> each row sums to 1, confirming valid probability distribution

[[0.65900114 0.24243297 0.09856589]
 [0.11314284 0.8360188  0.05083836]]
[1. 1.]


In [49]:
a = np.array([1, 5, 3, 8, 2])
b = np.array([2, 4, 3, 7, 9])

print(a > b)    # [False  True False  True False]
print(a == b)   # [False False  True False False]
print(a != b)   # [ True  True False  True  True]

[False  True False  True False]
[False False  True False False]
[ True  True False  True  True]


In [50]:
a = np.array([1, -2, 3, -4])

print(np.any(a < 0))   # True  -> at least one negative value exists
print(np.all(a > 0))   # False -> not all values are positive

True
False


In [51]:
X = np.array([[1.0, 2.0], [np.nan, 3.0], [4.0, 5.0]])

has_missing = np.any(np.isnan(X))
print(has_missing)  # True -> dataset has missing values, need to handle before training

True


In [52]:
a = np.array([1, -2, 3, -4, 5])

result = np.where(a > 0, a, 0)   # keep positive, replace negative with 0
print(result)  # [1 0 3 0 5]

# This is literally the ReLU activation function:
def relu(x):
    return np.where(x > 0, x, 0)

print(relu(np.array([-3, -1, 0, 2, 5])))  # [0 0 0 2 5]

[1 0 3 0 5]
[0 0 0 2 5]


In [53]:
data = np.array([10, 12, 200, 11, 9, -150, 13])
labels = np.where((data > 100) | (data < -100), "outlier", "normal")
print(labels)

['normal' 'normal' 'outlier' 'normal' 'normal' 'outlier' 'normal']


In [54]:
y_true = np.array([1, 0, 1, 1, 0, 1])
y_pred = np.array([1, 0, 0, 1, 0, 1])

correct = (y_true == y_pred)
accuracy = np.mean(correct)   # True=1, False=0, mean gives fraction correct
print(accuracy)  # 0.833...

0.8333333333333334
