In [2]:
import numpy as np

In [6]:
a=np.random.randint(1,100,size=(4,3))
print(a)

print(np.mean(a))
print(np.std(a))

standardize=(a-np.mean(a))/np.std(a)
print(standardize)

[[10 25 88]
 [24  7 88]
 [38 98 74]
 [86 58 33]]
52.416666666666664
31.93863473739741
[[-1.32806762 -0.85841699  1.11411567]
 [-0.88972703 -1.42199775  1.11411567]
 [-0.45138644  1.42721609  0.67577508]
 [ 1.05149558  0.1748144  -0.60793665]]


In [ ]:
a=np.random.randint(1,10,size=(3,1))
b=np.random.randint(1,20,size=(1,4))
print(a+b)

#we have studied that if there is 1 we have to not consider it, we have to choose corresponding values, so here we have 1 in a and 1 in b, so we have to choose corresponding values, so we have to choose 3 and 4, so the output will be 3+4=7, similarly for other values.

[[17 13 23 25]
 [14 10 20 22]
 [18 14 24 26]]


In [10]:
def relu_derivative(x):
    return np.where(x > 0, 1, 0)

x=np.array([1,2,3,4,5,0,1,0])

print(relu_derivative(x))

[1 1 1 1 1 0 1 0]


In [17]:
a=np.random.randint(1,10,size=(5,4))

row_sums = a.sum(axis=1, keepdims=True)  # shape (2,1)

normalized = a / row_sums   # (2,3) / (2,1) -> broadcasts correctly!
print(normalized)

[[0.33333333 0.33333333 0.11111111 0.22222222]
 [0.08333333 0.58333333 0.08333333 0.25      ]
 [0.41176471 0.11764706 0.05882353 0.41176471]
 [0.2        0.2        0.2        0.4       ]
 [0.3        0.16666667 0.3        0.23333333]]


In [18]:
y_true = np.array([1,1,0,1,0,0,1])
y_pred = np.array([1,0,0,1,0,1,1])


squared_error=(y_true-y_pred)**2
print(squared_error)
mse=np.mean(squared_error)
print(mse)


[0 1 0 0 0 1 0]
0.2857142857142857
