In [2]:
import numpy as np

In [ ]:
a = np.array([10, 20, 30, 40, 50])

print(a[0])      # 10 - first element
print(a[-1])     # 50 - last element
print(a[1:4])    # [20 30 40] - slice (start:stop, stop excluded)
print(a[:3])     # [10 20 30] - from beginning
print(a[2:])     # [30 40 50] - to end     
print(a[::2])    # [10 30 50] - every 2nd element
print(a[::-1])   # [50 40 30 20 10] - reversed

10
50
[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]
[50 40 30 20 10]


In [20]:
data = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])

print(data[0, 0])      # 1 - row 0, col 0
print(data[1, 2])      # 6 - row 1, col 2
print(data[2])         # [7 8 9] - entire row 2
print(data[:, 0])      # [1 4 7 10] - entire column 0
print(data[:, 1:3])    # all rows, columns 1-2
print(data[1:3, 0:2])  # rows 1-2, cols 0-1 (sub-matrix)

1
6
[7 8 9]
[ 1  4  7 10]
[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]
[[4 5]
 [7 8]]


In [27]:
dataset = np.array([[5.1, 3.5, 1.4, 0.2, 0],
                     [4.9, 3.0, 1.4, 0.2, 0],
                     [6.2, 3.4, 5.4, 2.3, 1]])

X = dataset[:, :-1]   # all rows, all columns except last -> features
y = dataset[:, -1]    # all rows, only last column -> labels

print(X)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [6.2 3.4 5.4 2.3]]
[0. 0. 1.]


In [36]:
tensor = np.arange(24).reshape(2, 3, 4)  # 2 blocks, 3 rows, 4 cols
print(tensor[0])          # first block (3x4 matrix)
print(tensor[0, 1])       # first block, second row
print(tensor[0, 1, 2])    # first block, second row, third element
print(tensor[:, :, 0])    # first column of every row in every block

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]
6
[[ 0  4  8]
 [12 16 20]]


In [ ]:
print(tensor[:,:,:])
print(tensor[0,2:3,1:2])
print(tensor[1,0,3])
print(tensor[1,1:3,:2])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[9]]
15
[[16 17]
 [20 21]]


In [ ]:
a = np.array([10, 15, 20, 25, 30, 35])

mask = a > 20
print(mask)        # [False False False  True  True  True]
print(a[mask])      # [25 30 35] - only elements where condition is True

# One-liner (very common style)
print(a[a > 20])    # same result

[False False False  True  True  True]
[25 30 35]
[25 30 35]


In [41]:
a = np.array([10, 15, 20, 25, 30, 35])

print(a[(a > 15) & (a < 30)])   # AND -> [20 25]
print(a[(a < 15) | (a > 30)])   # OR  -> [10 35]
print(a[~(a > 20)])             # NOT -> [10 15 20]

[20 25]
[10 35]
[10 15 20]


In [42]:
ages = np.array([25, -5, 34, 120, 45, 0, 67])

valid_ages=ages[(ages>0)&(ages<100)]
print(valid_ages)


[25 34 45 67]


In [43]:
X = np.array([[1,2], [3,4], [5,6], [7,8]])
y = np.array([0, 1, 0, 1])

x_class=X[y==0]
print(x_class)

[[1 2]
 [5 6]]


In [44]:
a = np.array([1, -2, 3, -4, 5])
a[a<0]=0  # replace all negative values with 0
print(a)  # [1 0 3 0 5]

[1 0 3 0 5]


In [45]:
a = np.array([10, 20, 30, 40, 50])

indices = [0, 2, 4]
print(a[indices])   # [10 30 50]

# Works in 2D too
data = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
rows = [0, 2, 3]
print(data[rows])   # picks rows 0, 2, 3

[10 30 50]
[[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]


In [3]:
X = np.array([[1,2], [3,4], [5,6], [7,8], [9,10]])
y = np.array([0, 1, 0, 1, 1])

np.random.seed(42)
indices = np.random.permutation(len(X))  # shuffled index order
print(indices)  # e.g. [1 4 2 0 3]

X_shuffled = X[indices]
y_shuffled = y[indices]
print(X_shuffled)
print(y_shuffled)

[1 4 2 0 3]
[[ 3  4]
 [ 9 10]
 [ 5  6]
 [ 1  2]
 [ 7  8]]
[1 1 0 0 1]


In [ ]:
data=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

print(data[[0,2],:])
print(data[[0,2],[0,1]])
print(data[np.ix_([0,2], [0,1])]) #give sub matrix with rows 0,2 and columns 0,1


[[1 2 3]
 [7 8 9]]
[1 8]
[[1 2]
 [7 8]]


In [51]:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]      # this is a VIEW, not a new array
b[0] = 999
print(a)  # [1 999 3 4 5] -> ORIGINAL CHANGED!

[  1 999   3   4   5]


In [50]:
a = np.array([1, 2, 3, 4, 5])
b = a[[0, 1, 2]]   # fancy indexing -> COPY
b[0] = 999
print(a)  # [1 2 3 4 5] -> unchanged

c = a[a > 2]       # boolean indexing -> COPY
c[0] = 999
print(a)  # [1 2 3 4 5] -> unchanged

[1 2 3 4 5]
[1 2 3 4 5]


In [52]:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
print(b.base is a)   # True -> b is a view of a
c = a[[0,1,2]]
print(c.base is a)   # False -> c is an independent copy

True
False


In [53]:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4].copy()   # explicit copy - safe, independent
b[0] = 999
print(a)  # [1 2 3 4 5] -> unaffected

[1 2 3 4 5]


In [58]:
X_train = np.random.rand(100, 5)
X_subset = X_train[:20].copy()  # explicit copy - safe to modify without side effects
X_subset[:, 0] = 0  # won't touch X_train

In [61]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])

v=np.vstack((a,b,c))
print(v)
print(v.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [65]:
a=np.array([1,2])
b=np.array([3,4])

h=np.hstack((a,b))

print(h)
print(h.shape)

[1 2 3 4]
(4,)


In [68]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

h=np.hstack((a,b))
print(h)


[[1 2 5 6]
 [3 4 7 8]]


In [71]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

c=np.concatenate((a,b),axis=0) # concatenate along rows (vertical)

c1=np.concatenate((a,b),axis=1) # concatenate along columns (horizontal)

print(c)
print(c1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
X = np.array([[1,2],[3,4],[5,6]])       # existing features
new_feature = np.array([[10],[20],[30]]) # new feature, shape (3,1)

X_new = np.hstack((X, new_feature))
print(X_new)


[[ 1  2 10]
 [ 3  4 20]
 [ 5  6 30]]


In [73]:
batch1 = np.random.rand(10, 5)  # 10 samples
batch2 = np.random.rand(15, 5)  # 15 samples
full_data = np.vstack((batch1, batch2))
print(full_data.shape)  # (25, 5)

(25, 5)


In [74]:
a = np.arange(9)
parts = np.split(a, 3)  # split into 3 EQUAL parts
print(parts)  # [array([0,1,2]), array([3,4,5]), array([6,7,8])]

# Split at specific indices
a = np.arange(10)
parts = np.split(a, [3, 7])  # split at index 3 and index 7
print(parts)  # [array([0,1,2]), array([3,4,5,6]), array([7,8,9])]

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]


In [75]:
data=np.arange(16).reshape(4,4)
print(data)

left,right=np.hsplit(data,2) #split into 2 equal parts horizontally
print(left)
print(right)

top,bottom=np.vsplit(data,2) #split into 2 equal parts vertically
print(top)
print(bottom)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [76]:
X = np.random.rand(100, 5)
y = np.random.randint(0, 2, 100)

split_idx = int(0.8 * len(X))  # 80% train, 20% test

X_train, X_test = X[:split_idx], X[split_idx:]
y_train, y_test = y[:split_idx], y[split_idx:]

print(X_train.shape, X_test.shape)  # (80, 5) (20, 5)

(80, 5) (20, 5)


In [77]:
a = np.array([5, 2, 8, 1, 9])
print(np.sort(a))       # [1 2 5 8 9]
print(a)                 # [5 2 8 1 9] -> unchanged

# In-place sort (modifies original)
a.sort()
print(a)  # [1 2 5 8 9]

[1 2 5 8 9]
[5 2 8 1 9]
[1 2 5 8 9]


In [ ]:
data = np.array([[3, 1, 2],
                  [9, 7, 8]])

print(np.sort(data, axis=1))  # sort each ROW independently
# [[1 2 3]
#  [7 8 9]]

print(np.sort(data, axis=0))  # sort each COLUMN independently
# [[3 1 2]
#  [9 7 8]]

[[1 2 3]
 [7 8 9]]
[[3 1 2]
 [9 7 8]]


In [83]:
a = np.array([50, 10, 40, 20, 30])
sorted_indices = np.argsort(a)
print(sorted_indices)  # [1 3 4 2 0] -> index of smallest, 2nd smallest, etc.
print(a[sorted_indices])  # [10 20 30 40 50] -> using indices to sort

[1 3 4 2 0]
[10 20 30 40 50]


In [86]:
# 1. Getting top-K predictions (e.g., top 3 highest probability classes)
probs = np.array([0.1, 0.7, 0.05, 0.15])
top_k_indices = np.argsort(probs)[::-1][:3]  # sort descending, take top 3
print(top_k_indices)  # [1 3 0] -> indices of top 3 probabilities

# 2. Sorting samples by a score while keeping labels aligned
scores = np.array([0.9, 0.3, 0.6])
labels = np.array(['cat', 'dog', 'bird'])

order = np.argsort(scores)[::-1]  # descending order of scores
print(labels[order])  # ['cat' 'bird' 'dog'] -> ranked by confidence

[1 3 0]
['cat' 'bird' 'dog']
