In [3]:
import numpy as np

In [ ]:
data=np.arange(1,26).reshape(5,5)

print(data) #original array

print(data[1:4,1:4]) # 3x3 sub array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [8]:
a = np.array([3, -1, 4, -1, 5, -9, 2, -6])

print(a[a>0])

a[a<0]=0

print(a)

[3 4 5 2]
[3 0 4 0 5 0 2 0]


In [13]:
X = np.random.rand(10, 3)
y = np.random.randint(0,2,10)

np.random.seed(42)
indices = np.random.permutation(len(X))  # shuffled index order
print(indices)  # e.g. [1 4 2 0 3]

X_shuffled = X[indices]
y_shuffled = y[indices]
print(X_shuffled)
print(y_shuffled)

[8 1 5 0 7 2 9 4 3 6]
[[0.85941973 0.13169654 0.82047154]
 [0.70269856 0.04019187 0.02959433]
 [0.12249946 0.31541799 0.28567141]
 [0.81256273 0.88139378 0.27597167]
 [0.15086899 0.3391977  0.62747673]
 [0.49476383 0.93234934 0.42441434]
 [0.84063965 0.57150766 0.50539038]
 [0.54730658 0.2131301  0.90495227]
 [0.98491397 0.77240021 0.0067995 ]
 [0.91790244 0.56970188 0.76959323]]
[1 0 1 1 0 0 1 0 1 0]


In [10]:
a=np.arange(10)

b=a[2:5]
b[0]=100

print(a)

#because here we have used the slicing method which is a view of the original array. So, when we change the value of b, it also changes the value of a. to keep it unchanges we have to use the fancy indexing method.

a=np.arange(10)

b=a[[2,3,4]]
b[0]=100

print(a)


[  0   1 100   3   4   5   6   7   8   9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
scores = np.array([65, 90, 78, 82, 55, 95])

indices=np.argsort(scores)[::-1][:3]

print(indices)

print(scores[indices])

[5 1 3]
[95 90 82]
