In [2]:
import numpy as np
import time

# Python list approach
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x + y for x, y in zip(list1, list2)]
print("Python list time:", time.time() - start)

# NumPy approach
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
result = arr1 + arr2
print("NumPy time:", time.time() - start)

Python list time: 0.06279158592224121
NumPy time: 0.010374784469604492


In [7]:
a=np.array([1,2,3,4,5])
print(a)

b=np.array([[1,2,3],
            [4,5,6]])
print(b)

c=np.array([[[1,2],[3,4]],
            [[5,6],[7,8]]])
print(c.shape)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
(2, 2, 2)


In [8]:
zeros=np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
ones=np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
filled=np.full((2,2),9)
print(filled)

[[9 9]
 [9 9]]


In [13]:
identity=np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
r=np.arange(0,10,2)
print(r)

print(r[1]-r[0])

[0 2 4 6 8]
2


In [25]:
lin=np.linspace(0,1,5)
print(lin)

print(lin[2]-lin[1])

[0.   0.25 0.5  0.75 1.  ]
0.25


In [ ]:
empty=np.empty((2,2))
print(empty)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [28]:
print(np.arange(0, 1, 0.3))       # [0.  0.3 0.6 0.9]  - step-based
print(np.linspace(0, 1, 4))       # [0.    0.333 0.667 1.]  - count-based, includes endpoint

[0.  0.3 0.6 0.9]
[0.         0.33333333 0.66666667 1.        ]


In [81]:
np.random.seed(42)

In [31]:
rand_arr=np.random.rand(3,3)
print(rand_arr)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [82]:
randn_arr=np.random.randn(3,3)
print(randn_arr)

mean=np.mean(rand_arr)
print(mean)

std=np.std(rand_arr)
print(std)

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]
0.4992549757478559
0.30888608340705315


In [4]:
randint_arr=np.random.randint(0,10, size=(3,3))
print(randint_arr)

[[6 2 4]
 [0 0 1]
 [6 7 3]]


In [ ]:
np.random.seed(42)  # reproducibility - CRITICAL in ML experiments

rand_arr = np.random.rand(3, 3)      # uniform [0,1)
randn_arr = np.random.randn(3, 3)    # standard normal (mean=0, std=1)
randint_arr = np.random.randint(0, 10, size=(3, 3))  # random integers

In [89]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.shape)      # (2, 3) - dimensions (rows, cols)
print(a.ndim)        # 2 - number of dimensions/axes
print(a.size)        # 6 - total number of elements
print(a.dtype)        # int64 (or int32 on some systems) - data type
print(a.itemsize)     # 8 - bytes per element
print(a.nbytes)       # 48 - total bytes (size * itemsize)

(2, 3)
2
6
int64
8
48


In [95]:
X=np.random.rand(100,5)
weight=np.random.rand(5,1)

print(X.shape, weight.shape)
predictions=np.dot(X,weight)
print(predictions.shape)
predictions=X @weight
print(predictions.shape)

(100, 5) (5, 1)
(100, 1)
(100, 1)


In [96]:
# Real debugging example
X = np.random.rand(100, 5)   # 100 samples, 5 features
weights = np.random.rand(5, 1)  # 5 features -> 1 output

print(X.shape, weights.shape)  # (100, 5) (5, 1)
predictions = X @ weights       # matrix multiply works because inner dims match (5 == 5)
print(predictions.shape)        # (100, 1)

(100, 5) (5, 1)
(100, 1)


In [103]:
a = np.array([1, 2, 3])
print(a.dtype)  # int64

b = np.array([1.0, 2.0, 3.0])
print(b.dtype)  # float64

c = np.array([1, 2, 3], dtype=np.float32)  # explicitly set dtype
print(c.dtype)  # float32

d = np.array([True, False, True])
print(d.dtype)  # bool

int64
float64
float32
bool


In [105]:
a=np.array([1.7,2.3,3.9])
b=a.astype(np.int32)
print(b)
print(b.dtype)

[1 2 3]
int32


In [107]:
img=np.array([0,128,255], dtype=np.uint8)
img_float=img.astype(np.float32)/255.0
print(img_float)

[0.        0.5019608 1.       ]


In [108]:
a = np.array([1.7, 2.3, 3.9])
b = a.astype(np.int32)
print(b)  # [1 2 3] - truncates, doesn't round!

# Common ML pattern: normalize image data
img = np.array([0, 128, 255], dtype=np.uint8)
img_float = img.astype(np.float32) / 255.0
print(img_float)  # [0.  0.502 1. ]

[1 2 3]
[0.        0.5019608 1.       ]


In [109]:
a = np.array([200, 100], dtype=np.uint8)
print(a + 100)  # [44 200] - WRAPS AROUND! 200+100=300 overflows uint8 (max 255)

[ 44 200]


In [120]:
a=np.arange(12)
print(a)
print(a.shape)

b=a.reshape(3,4)
print(b)
print(b.shape)
c=a.reshape(4,3)
print(c)
print(c.shape)

d=a.reshape(2,2,3)
print(d)
print(d.shape)

e=a.reshape(3,2,2)
print(e)
print(e.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
(3, 2, 2)


In [121]:
a = np.arange(12)  # [0 1 2 ... 11]
print(a.shape)  # (12,)

b = a.reshape(3, 4)  # 3 rows, 4 cols
print(b)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

c = a.reshape(2, 3, 2)  # 3D
print(c.shape)  # (2, 3, 2)

(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(2, 3, 2)


In [124]:
a=np.arange(12)
b=a.reshape(3,-1)
print(b.shape)

c=a.reshape(-1,4)
print(c.shape)

(3, 4)
(3, 4)


In [125]:
images = np.random.rand(32, 28, 28)  # 32 images, 28x28 pixels
flattened = images.reshape(32, -1)   # (32, 784) - each image is now a flat vector
print(flattened.shape)

(32, 784)


In [ ]:
a = np.array([[1, 2], [3, 4]])

f = a.flatten()   # ALWAYS returns a COPY
r = a.ravel()     # returns a VIEW when possible (no data copy → faster)

f[0]=100
print(a) #a IS NOT MODIFIED, because flatten returns a copy
print(f) 
print(r)

r[0] = 99
print(a)  # a IS MODIFIED, because ravel shares memory
# [[99  2]
#  [ 3  4]]



[[1 2]
 [3 4]]
[100   2   3   4]
[1 2 3 4]
[[99  2]
 [ 3  4]]


In [ ]:
a2=np.array([[1,2],[3,4]])
f2=a2.flatten()
f2[0]=100
print(a2) # a2 is not modified, because flatten returns a copy

[[1 2]
 [3 4]]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])

print(a.shape)
print(a.T.shape)
print(a) # Original array
print(a.T) # Transpose of the array

(2, 3)
(3, 2)
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [136]:
X=np.random.rand(100,5)
W=np.random.rand(3,5)

output=X @ W.T

print(output.shape)

(100, 3)


In [137]:
X = np.random.rand(100, 5)      # 100 samples, 5 features
W = np.random.rand(3, 5)        # 3 neurons, 5 weights each

output = X @ W.T                # (100,5) @ (5,3) = (100, 3)
print(output.shape)

(100, 3)
