In [2]:
import numpy as np

In [4]:
identity=np.eye(4,4)

multi=identity * 5

print(multi)

[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


In [8]:
lin=np.linspace(-1,1,20) 
print(lin)

[-1.         -0.89473684 -0.78947368 -0.68421053 -0.57894737 -0.47368421
 -0.36842105 -0.26315789 -0.15789474 -0.05263158  0.05263158  0.15789474
  0.26315789  0.36842105  0.47368421  0.57894737  0.68421053  0.78947368
  0.89473684  1.        ]


In [17]:
arr=np.array([[[1,2,3,4],
               [5,6,6,4],
               [3,6,9,5]],
               
               [[3,4,5,2],
                [3,6,8,6],
                [3,1,6,1]]
               ])
print(arr)
flat=arr.flatten()
print(flat)
r=flat.reshape(4,6)

print(r)

[[[1 2 3 4]
  [5 6 6 4]
  [3 6 9 5]]

 [[3 4 5 2]
  [3 6 8 6]
  [3 1 6 1]]]
[1 2 3 4 5 6 6 4 3 6 9 5 3 4 5 2 3 6 8 6 3 1 6 1]
[[1 2 3 4 5 6]
 [6 4 3 6 9 5]
 [3 4 5 2 3 6]
 [8 6 3 1 6 1]]


In [28]:
arr=np.random.randint(0,9,(2,3,4))
print(arr)
flat=arr.flatten()
print(flat)
reshape=flat.reshape(4,6)
print(reshape)

[[[7 8 8 8]
  [6 1 5 4]
  [1 4 4 7]]

 [[8 3 7 7]
  [8 3 3 4]
  [1 3 8 0]]]
[7 8 8 8 6 1 5 4 1 4 4 7 8 3 7 7 8 3 3 4 1 3 8 0]
[[7 8 8 8 6 1]
 [5 4 1 4 4 7]
 [8 3 7 7 8 3]
 [3 4 1 3 8 0]]


In [18]:
arr=np.array([250,10],dtype=np.uint8)
print(arr+10)

[ 4 20]


In [31]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
arr1=np.random.randint(1,10,(5,3))
print(arr)
print(arr1)
print(arr.shape)
print(arr1.shape)

t=arr.T
print(t.shape)
t1=arr1.T
print(t1.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[2 2 6]
 [8 9 4]
 [7 7 9]
 [3 2 1]
 [6 3 7]]
(5, 3)
(5, 3)
(3, 5)
(3, 5)
